apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificationservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notificationservice
  template:
    metadata:
      labels:
        app: notificationservice
    spec:
      containers:
        - name: notificationservice
          image: afra1507/notificationservice:latest
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/guru_notificationdb
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: ""
            - name: GMAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: gmail-secret
                  key: username
            - name: GMAIL_APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gmail-secret
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: notificationservice
spec:
  selector:
    app: notificationservice
  ports:
    - port: 8084
      targetPort: 8084
  type: ClusterIP
